In [2]:
import torch
import torch.nn as nn

建立一个MLP多层感知机

In [7]:
class MyLinear(nn.Module):
    def __init__(self,in_features,hidden_features,out_features):
        # 定义构造方法
        super().__init__() # 固定写法，让 PyTorch 正确管理模型

        self.net = nn.Sequential(
            nn.Linear(in_features,hidden_features),
            nn.ReLU(), # 激活函数让模型可以学习非线性函数，否则MLP就是Linear，非负数不变
            nn.Linear(hidden_features,out_features)
        )
    
    def forward(self,x):
        return self.net(x) # 直接调用Sequential对象就可以了


In [11]:
x = torch.arange(12, dtype=torch.float32).reshape(3,4) # 生成一个3*4的矩阵
y = torch.arange(12, dtype=torch.float32).reshape(3,4) * 2 + 5 # 生成一个3*4的矩阵

module = MyLinear(in_features=4,hidden_features=5,out_features=4) # 4->5->4
y_pred = module(x) # 前向传播
loss = ((y_pred - y)**2).mean() # 计算均方误差
loss.backward() # 反向传播，计算梯度
print(module.net[0].weight.grad) # 打印第一层的权重梯度
print(module.net[0].bias.grad) # 打印第一层的偏置梯度

y_pred  # grad_fn=<AddmmBackward0>说明这个输出是由可求导的计算产生的

tensor([[23.0594, 27.5317, 32.0040, 36.4764],
        [ 0.0000, -0.3408, -0.6816, -1.0224],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
tensor([ 4.4723, -0.3408,  0.0000,  0.0000,  0.0000])


tensor([[-0.0206, -0.2707, -0.4302,  0.2197],
        [ 0.0049, -0.1643, -0.8147, -0.3238],
        [ 0.1801, -0.2283, -1.2100, -0.7351]], grad_fn=<AddmmBackward0>)

In [10]:
for name,param in module.named_parameters():
    print(name,param.shape) # 打印参数的名字和形状

net.0.weight torch.Size([5, 4])
net.0.bias torch.Size([5])
net.2.weight torch.Size([4, 5])
net.2.bias torch.Size([4])
